export const DISCOVERY = {
  CACHE_TTL_MS: 5 * 60 * 1000,
  MAX_DISCOVERED_PEERS: 1000,
  DIAL_QUEUE_TICK_MS: 200,
  DIAL_MAX_CONCURRENT: 4,
  DIAL_BACKOFF_BASE_MS: 250,
  DIAL_BACKOFF_MAX_MS: 5000,
} as const

export const SETTLEMENT = {
  WORKER_INTERVAL_MS: 5000,
  TIMEOUT_MS: 30000,
  DEFAULT_MAX_RETRIES: 3,
} as const

export const MESSAGING = {
  MAX_TIMESTAMP_DRIFT_MS: 5 * 60 * 1000,
  MAX_MESSAGE_AGE_MS: 60 * 60 * 1000,
} as const

export const BLOOM_FILTER = {
  DEFAULT_SIZE: 1024,
  DEFAULT_HASH_COUNT: 7,
  DEFAULT_GOSSIP_INTERVAL_MS: 300000,
  MAX_SIZE: 8192,
  REPUTATION_FILTERS_TOPIC: 'ecco:reputation-filters',
} as const

export const REPUTATION = {
  DEFAULT_COMMIT_THRESHOLD: 10,
  DEFAULT_COMMIT_INTERVAL_MS: 24 * 60 * 60 * 1000,
  DEFAULT_SYNC_INTERVAL_MS: 5 * 60 * 1000,
  MAX_PENDING_RATINGS: 1000,
  MIN_LOCAL_SCORE: -1000,
  MAX_LOCAL_SCORE: 1000,
} as const

export const STATE = {
  MAX_CAS_RETRIES: 100,
  CAS_BACKOFF_STEP_MS: 1,
  MAX_CAS_BACKOFF_MS: 10,
  MAX_SAFE_VERSION: Number.MAX_SAFE_INTEGER - 1,
  DEFAULT_MAX_PEERS: 10000,
  DEFAULT_STALE_PEER_TIMEOUT_MS: 30 * 60 * 1000,
  DEFAULT_DEDUP_MAX_MESSAGES: 10000,
  DEFAULT_DEDUP_FALSE_POSITIVE_RATE: 0.01,
  DEFAULT_RATE_LIMIT_MAX_TOKENS: 100,
  DEFAULT_RATE_LIMIT_REFILL_RATE: 10,
  DEFAULT_RATE_LIMIT_REFILL_INTERVAL_MS: 1000,
} as const

export const PEER_PERFORMANCE = {
  WEIGHTS: {
    SUCCESS: 50,
    ERROR: 30,
    LATENCY: 20,
  },
  MAX_LATENCY_MS: 10000,
} as const

export const IDENTITY = {
  SCRYPT_N: 16384,
  SCRYPT_R: 8,
  SCRYPT_P: 1,
  KEY_LENGTH: 32,
  SALT_LENGTH: 32,
  IV_LENGTH: 12,
  AUTH_TAG_LENGTH: 16,
  ENTROPY_TEST_SIZE: 32,
  MIN_UNIQUE_BYTES_RATIO: 0.25,
} as const

export const DHT = {
  MAX_PROVIDERS_DEFAULT: 100,
  MAX_PROVIDERS_WITH_SCORER: 500,
  MAX_CAPABILITIES_PER_PEER: 50,
} as const
